### ISSUE TITLE
properly use chart.js in vue

### ISSUE THREAD

**Issue by JeffaloBob** [JeffaloBob/ocular#25]
i really need some help with this.

i want to use chart.js inside of vue properly. i'm having a lot of issues with the way im trying to do it, where the load animation doesn't happen which is sad. i dont think vue was designed to work with chart.js and thats really annoying.

please someone help thanks

**Comment by hamptonmoore** [comment]
https://vue-chartjs.org/guide/#browser might be useful

**Comment by JeffaloBob** [comment]
> https://vue-chartjs.org/guide/#browser might be useful

thanks its kinda complicated though.


anyways i solved this with some documentation following and im very happy!!!
