### ISSUE TITLE
cannot log in

### ISSUE THREAD

**Issue by garnetluvcookie** [JeffaloBob/ocular#27]

**Comment by YOYITsM3M8** [comment]
Same

**Comment by Nagol12344** [comment]
auth loop

**Comment by JeffaloBob** [comment]
explain further?

**Comment by YOYITsM3M8** [comment]
When you verify it doesn’t work

**Comment by Nagol12344** [comment]
i use it auth thing and it brings me back to type in my username again i do and brings me back to the auth thing

**Comment by YOYITsM3M8** [comment]
Sameeee

**Comment by JeffaloBob** [comment]
i believe the original issue that @garnetluvcookie was reporting was just a miscommunication on fluffyscratch's side, the code received must be inputted into the project, not the comments. 
![image](https://user-images.githubusercontent.com/40470736/96132197-668c0f80-0efa-11eb-9f74-d95f349eec7f.png)
please make a new issue if that's not the issue that you're facing

**Comment by Nagol12344** [comment]
i am not i am putting in to the project

**Comment by JeffaloBob** [comment]
> i am not i am putting in to the project

please make a new issue explaining the problem in detail

**Comment by YOYITsM3M8** [comment]
I made new issue
