### ISSUE TITLE
bug logging in

### ISSUE THREAD

**Issue by YOYITsM3M8** [JeffaloBob/ocular#28]
**Describe the bug**
it won’t let me log in

**To Reproduce**
1. Go to 'https://myocular.jeffalo.net/login'
2. Type user name in box
3. Get code
4. Do the scratch project
5. Go back to jeffalo website
6. Press the other button
7. It asks you to login again

**Expected behavior**
Log me in

**Screenshots**
No

**Desktop (please complete the following information):**
 - OS: iOS
 - Browser chrome
 - Version newest 

**Smartphone (please complete the following information):**
 - Device: iPad 5th gen 
 - OS: iOS 
 - Browser: chrome
 - Version newest

**Additional context**
I’m sad 😢

**Comment by JeffaloBob** [comment]
perhaps this is an issue with cookies. can someone else with an ipad and chrome try to repro this?

**Comment by YOYITsM3M8** [comment]
I tried like 50 times

**Comment by Nagol12344** [comment]
i have done it on a chromebook and it dose not work

**Comment by JeffaloBob** [comment]
> i have done it on a chromebook and it dose not work

are you experiencing the same issue (with same repro steps) as YOYITsM3M8?

**Comment by Nagol12344** [comment]
yes

**Comment by YOYITsM3M8** [comment]
Jeffalo, does it work for you?

**Comment by JeffaloBob** [comment]
> Jeffalo, does it work for you?

yes, and i also asked someone to try to repro on chrome on ipad and they could log in fine.

are cookies being blocked for myocular.jeffalo.net?

**Comment by Nagol12344** [comment]
no

**Comment by JeffaloBob** [comment]
if possible, can one of you make some kind of screen recording or something demonstrating the issue?

**Comment by Nagol12344** [comment]
i can at 2:40

**Comment by Nagol12344** [comment]
i can

**Comment by YOYITsM3M8** [comment]
Wtf it worked

**Comment by hamptonmoore** [comment]
I am sorry, the issue is likely on my end. I will look at the logs and I have some planned steps to improve the login system

**Comment by Nagol12344** [comment]
its me the same thing happend on my end lol

**Comment by YOYITsM3M8** [comment]
No

**Comment by JeffaloBob** [comment]
> its me the same thing happend on my end lol

@Nagol12344 looking through the logs, i can see you're logging in with the n capitalized, but your scratch username is all lowercase. try logging in with your name all lowercase.

**Comment by Nagol12344** [comment]
i did

**Comment by JeffaloBob** [comment]
> i did

and it worked?

**Comment by Nagol12344** [comment]
yep

**Comment by Nagol12344** [comment]
you cant see that on the log

**Comment by hamptonmoore** [comment]
Sorry about that everyone. I will be refactoring the login system this weekend to fix that issue

**Comment by JeffaloBob** [comment]
in the latest commit to my-ocular (currently private) i added a system for displaying errors, hopefully this makes it a bit clearer.
![image](https://user-images.githubusercontent.com/40470736/96148665-c5588580-0f08-11eb-9adc-0a47357b72ac.png)
